version: '3.9'

services:
    nginx:
        image: nginx:1.24-alpine
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        build:
            dockerfile: docker/php-fpm/Dockerfile
            context: .
        volumes:
            - ./:/var/www/html

    mailer:
        image: yappabe/mailcatcher
        ports:
            - '81:1080'
        tty: true

volumes:
    database_data:
